services:
  orchid:
    build:
      context: ./
      network: host
    environment:
      - "ORCHID__APIS__FALCON__HOST=${ORCHID__APIS__FALCON__HOST:-localhost}"
      - "ORCHID__APIS__FALCON__PATH=${ORCHID__APIS__FALCON__PATH:-}"
      - "ORCHID__APIS__FALCON__PORT=${ORCHID__APIS__FALCON__PORT:-20100}"
      - "ORCHID__APIS__FALCON__SCHEME=${ORCHID__APIS__FALCON__SCHEME:-http}"
      - "ORCHID__APIS__ICANHAZDADJOKE__HOST=${ORCHID__APIS__ICANHAZDADJOKE__HOST:-icanhazdadjoke.com}"
      - "ORCHID__APIS__ICANHAZDADJOKE__PATH=${ORCHID__APIS__ICANHAZDADJOKE__PATH:-}"
      - "ORCHID__APIS__ICANHAZDADJOKE__PORT=${ORCHID__APIS__ICANHAZDADJOKE__PORT:-}"
      - "ORCHID__APIS__ICANHAZDADJOKE__SCHEME=${ORCHID__APIS__ICANHAZDADJOKE__SCHEME:-https}"
      - "ORCHID__DEBUG=${ORCHID__DEBUG:-true}"
      - "ORCHID__OIDC__GOOGLE__DOMAIN=${ORCHID__OIDC__GOOGLE__DOMAIN:-}"
      - "ORCHID__SECRETS__SHARED=${ORCHID__SECRETS__SHARED:-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}"
      - "ORCHID__SERVER__HOST=${ORCHID__SERVER__HOST:-0.0.0.0}"
      - "ORCHID__SERVER__PORT=${ORCHID__SERVER__PORT:-20120}"
      - "ORCHID__URLS__CROCUS__HOST=${ORCHID__URLS__CROCUS__HOST:-localhost}"
      - "ORCHID__URLS__CROCUS__PATH=${ORCHID__URLS__CROCUS__PATH:-}"
      - "ORCHID__URLS__CROCUS__PORT=${ORCHID__URLS__CROCUS__PORT:-20020}"
      - "ORCHID__URLS__CROCUS__SCHEME=${ORCHID__URLS__CROCUS__SCHEME:-http}"
      - "ORCHID__URLS__FALCON__HOST=${ORCHID__URLS__FALCON__HOST:-localhost}"
      - "ORCHID__URLS__FALCON__PATH=${ORCHID__URLS__FALCON__PATH:-}"
      - "ORCHID__URLS__FALCON__PORT=${ORCHID__URLS__FALCON__PORT:-20100}"
      - "ORCHID__URLS__FALCON__SCHEME=${ORCHID__URLS__FALCON__SCHEME:-http}"
      - "ORCHID__URLS__ORCHID__HOST=${ORCHID__URLS__ORCHID__HOST:-localhost}"
      - "ORCHID__URLS__ORCHID__PATH=${ORCHID__URLS__ORCHID__PATH:-}"
      - "ORCHID__URLS__ORCHID__PORT=${ORCHID__URLS__ORCHID__PORT:-20120}"
      - "ORCHID__URLS__ORCHID__SCHEME=${ORCHID__URLS__ORCHID__SCHEME:-http}"
    network_mode: host
